### ISSUE TITLE
TASK: Reenable ELN container image generation

### ISSUE THREAD

**Issue by mh21** [fedora-eln/eln#82]
### What does the ELN SIG need to do?
* The container images at https://quay.io/repository/fedoraci/fedora?tag=eln-x86_64&tab=tags were last generated over a month ago, on 2021-12-09, and are still incomplete.

**Comment by sgallagher** [comment]
I'm aware of this. We have been having some issues related to OpenSSL 3.0 and a stricter linker in Rawhide/ELN that I've been untangling. I'll have this back up and running ASAP.

**Comment by jkonecny12** [comment]
Not sure if it's related but our ELN tests started to fail on rpmbuild calls. I guess there is issue with something outdated? I'll see if it gets solved when there will be a new ELN image.

**Comment by sgallagher** [comment]
> Not sure if it's related but our ELN tests started to fail on rpmbuild calls. I guess there is issue with something outdated? I'll see if it gets solved when there will be a new ELN image.

This is due to an issue with the ima-evm-utils update. I'm on it.

**Comment by VladimirSlavik** [comment]
It seems that this has been solved since January, I get images that are <24 hours old.

**Comment by mh21** [comment]
The image tagged with `:eln` still does not contain the `s390x` architecture 🙈.

**Comment by sgallagher** [comment]
Yeah, I'm still working on this. The s390x and aarch64 container base images aren't building successfully, but I haven't been able to figure out why yet. For example: https://koji.fedoraproject.org/koji/taskinfo?taskID=91535574

**Comment by yselkowitz** [comment]
Wasn't the kiwi migration going to solve this too?

**Comment by sgallagher** [comment]
We've had container base images building on all arches since before the Kiwi migration, actually. But right now we have a different problem where we aren't actually uploading images anywhere...

That's being tracked in https://pagure.io/cloud-image-uploader/issue/26

**Comment by yselkowitz** [comment]
Images are being uploaded regularly to https://quay.io/repository/fedora/eln.  Anything remaining here?

**Comment by sgallagher** [comment]
Nope, I think we're good here now.
